version: "3"
services:
  hub:
    image: seleniarm/hub:latest
  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: seleniarm/node-firefox:latest
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env